### ISSUE TITLE
Fast Download feature PLEASE

### ISSUE THREAD

**Issue by z9z9z9z9z9z9** [pyrohost/pyrodactyl#110]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

can the kind creators please implement FastDL feature. (Fast Download) it's really important for servers to have FastDL :') (CS:GO, Cs 1.6 and many other games) 

### Describe the solution you'd like.

please add FastDL , (Auto Fastdl for every server) usually in server.cfg im sue yall know ab it

**Comment by naterfute** [comment]
I think this is something you should make a request for in the pterodactyl eggs repository, as I'm pretty sure this is something that needs to be implemented on the server side rather than the panel's side.

Correct me if I'm wrong of course, as I've never hosted a counter strike server, I could be mistaken.

https://github.com/pelican-eggs/games-steamcmd

**Comment by Thr33Tree** [comment]
Correct me if I am wrong but.

I've used Fast-Dl before in gmod and all it needs is a HTML server that can serve files. I'm not too certain about other source games or even gold source games

**Comment by naterfute** [comment]
Ah, I see now. I believe the best and safest course of action, would be to get a nginx, apache, traefik, or any other web server egg, and deploy it to your node. This will keep it dockerized of course, and it will keep in manageable from the panel still.

I found an [nginx egg](https://github.com/Sigma-Production/ptero-eggs) if you want one, I'm sure you can find the others just by looking, the pterodcatyl community is quite large after all.

**Comment by naterfute** [comment]
I think this issue has been resolved as there is no more comments on it.
