### ISSUE TITLE
Server nav bar isnt shown on mobile version (only tested on chrome on android)

### ISSUE THREAD

**Issue by MindlessGamingDE** [pyrohost/pyrodactyl#121]
### Current Behavior

if i wanna manage a server i cant see the navigation bar on the /server/<id> site

### Expected Behavior

I expect, that i can see the navigation bar to jump around the sites and fully manage my server.

### Steps to Reproduce

go on the phone on a server to manage it and there should be no navigation bar.

### Panel Version

3.0.0

### Wings Version

1.11.13

### Games and/or Eggs Affected

none only the panel

### Docker Image

none only the panel

### Error Logs

```bash
-
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by naterfute** [comment]
This was my bad, when I made the push to add sidebar support for mobile, I forgot to update the ServerRouter, i'm pushing a fix now
