### ISSUE TITLE
More help in the developer Server Config

### ISSUE THREAD

**Issue by KushiKreates** [pyrohost/pyrodactyl#123]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

**When starting a dev server this could be great help as artisan's server doesn't use SSL,** 

### Describe the solution you'd like.

But instead of that why not use Symphony? symfony server:start, this could be helpful for ppl struggling w/ ssl issues 

### Additional context to this request.

Im sorry, its a really picky thing but help, I hope atleast one person needs it!

**Comment by naterfute** [comment]
I'm sorry, why would normal people need to start a dev server with ssl?

**Comment by KushiKreates** [comment]
Sometimes, There are times where ppl who edit pyro need to yk run a dev server, I know nix does that very well But I myself don't use it but simply just run it on wsl with the packages and just npm run dev and symfony server:start, I used to use artisan serve but got so irritated of the constant the connection to this server isn't same BS, So ye. Im sorry if this is a picky one :(

**Comment by naterfute** [comment]
I don't think this is worth the trouble. Off you want to make a pr I'll take a look. But other then that I going think adding ssl support to the dev server is something meant people will need. I've been trying to focus on fixing the glaring issues in the panel
