### ISSUE TITLE
Ability to disable Server Egg Changer

### ISSUE THREAD

**Issue by AwesomeKalin** [pyrohost/pyrodactyl#129]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I don't want the server egg changer available to customers directly, so I want to be able to disable it

### Describe the solution you'd like.

A setting that lets you disable the server software changer

**Comment by naterfute** [comment]
Hmm, if You don't mind me asking, why would you not want them to be able to access this?

That being said, depending on how you are supplying servers to your customers you can just disable the ability to let them change the software in the permssions tab 
![image](https://github.com/user-attachments/assets/383e47f4-3866-45ce-8f42-8fbec7d67d0a)
