### ISSUE TITLE
Layout  of /account/api and /account/ssh

### ISSUE THREAD

**Issue by Fafikk** [pyrohost/pyrodactyl#139]
### Current Behavior

Layout of pages /account/api and /account/ssh looks strange.
![image](https://github.com/user-attachments/assets/9e38ab4b-8bef-42f4-9bd4-1979932fb0ab)
![image](https://github.com/user-attachments/assets/849d5a3c-040e-45f3-a208-5ec77e5f6e19)

### Expected Behavior

I expected UI to look normally.

### Steps to Reproduce

Fix the UI.

### Panel Version

3.0.0

### Wings Version

1.11

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by naterfute** [comment]
I. uhh. Didn't even know this page existed, I don't think there is a way to navigate to it from normal navbar, is there.

**Comment by Fafikk** [comment]
No, its not possible to navigate to that page from any navbar.

**Comment by naterfute** [comment]
Cool, let me get working on fixing that. I was wondering why these routes didn't exist :rofl: But I just was to busy with other stuff to go looking into them
