### ISSUE TITLE
UI Spacing on the SSH Keys tab is wrong

### ISSUE THREAD

**Issue by IThundxr** [pyrohost/pyrodactyl#149]
### Current Behavior

![image](https://github.com/user-attachments/assets/27bd6c2d-df00-4482-a8ff-d852de9f26cb)
Currently the text boxes are far too close to the text itself (This affects the api keys page aswell) and the sha256 and date overlap each other

### Expected Behavior

There should be some spacing between the text boxes and the text itself and the ssh keys section should be a bit larger to handle displaying the sha256 and date cleanly

### Steps to Reproduce

Log into the panel and navigate to the SSH keys section, and then add a new ssh key

### Panel Version

3.0.0 - Build 300000, Commit ca9b7b9

### Wings Version

N/A

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by he3als** [comment]
> Yup, I'm going to rework this entire page. Same with the API page. Just like many things in this project since I took over, I just made a quick and dirty fix to make it work until I can make a more permanent one, I'll reference this issue to track progress.

Maybe make the keys pages similar to the database & users pages?

**Comment by naterfute** [comment]
I got some feedback from Ellie on this, I have a plan for it. If I do good I get a Cookie 🍪
