### ISSUE TITLE
Wiki: Upgrading from Pterodactyl to Pyrodactyl ( Non-Docker )

### ISSUE THREAD

**Issue by a8b1** [pyrohost/pyrodactyl#163]
### Current Behavior

When I run `git clone https://github.com/pyrohost/pyrodactyl.git /var/www/pterodactyl --depth=2` it's returning an error shown below
```
fatal: destination path '/var/www/pterodactyl' already exists and is not an empty directory.
```

### Expected Behavior

download the git repo

### Solution
create release on latest stable version of pyrodactyl in `tar.gz` and use the curl command shown in the documentation with a small change
```sh
curl -L https://github.com/pyrohost/pyrodactyl/releases/latest/download/panel.tar.gz | tar -xzv
```

I think that's all 

### Steps to Reproduce

https://github.com/pyrohost/pyrodactyl/wiki/Installation#non-docker

do the first command on an existing pterodactyl panel server

### Panel Version

1.11

### Wings Version

1.11

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by naterfute** [comment]
You already have pterodactyl installed in that directory. You can't install something in the same spot

**Comment by a8b1** [comment]
But it's for existing pterodactyl users? (quick install)
https://github.com/pyrohost/pyrodactyl/wiki/Installation#non-docker

**Comment by naterfute** [comment]
In my defense, I suck at writing docs and am currently working on a better system, apologies.
